package com.sunrise.dental.dao;

import com.sunrise.dental.exception.ApplicationException;
import com.sunrise.dental.model.Prescription;
import com.sunrise.dental.model.PrescriptionItem;
import java.util.List;

/**
 * PrescriptionDAO — Data Access Object interface for Prescriptions.
 */
public interface PrescriptionDAO {

    /** Save a new prescription. Returns generated prescription_id. */
    int save(Prescription prescription) throws ApplicationException;

    /** Save an item inside a prescription. */
    void saveItem(PrescriptionItem item) throws ApplicationException;

    /** Find a prescription by ID (includes populated items list). */
    Prescription findById(int prescriptionId) throws ApplicationException;

    /** Fetch all prescriptions for a specific patient. */
    List<Prescription> findByPatientId(int patientId) throws ApplicationException;

    /** Fetch all prescriptions generated by a specific dentist. */
    List<Prescription> findByDentistId(int dentistId) throws ApplicationException;

    /** Search prescriptions with query and pagination. */
    List<Prescription> search(String query, int offset, int limit) throws ApplicationException;

    /** Count search results. */
    int countSearch(String query) throws ApplicationException;

    /** Generate next prescription number, e.g. RX-2026-000001 */
    String generatePrescriptionNumber() throws ApplicationException;
}
